### ISSUE TITLE
support

### ISSUE THREAD

**Issue by Gembeltz** [SleepMod/Overwrite-MBR#1]
how if  open a malware MBR with a random password like the petya ransomware ? @SleepMod

**Comment by SleepMod** [comment]
Ok, for the random password i think you need to use a function (idk name). For Petya mbr payload you need to use 4 BIOS interruptions: 
Int 10h: print msg on screen
Int 13h: to read sectors and jump it to read msg and others, including the msg
Int 16h: for keyboard usage "important for user to enter the key"
Int 19h: reboot computer after salsa20 MFT encryption

Im working on a project with similar functions, and i will use int 16h and 13h like Petya.

**Comment by Gembeltz** [comment]
Nice @SleepMod  
I'm waiting for your project :*

**Comment by SleepMod** [comment]
@Gembeltz, the soucre code of int 0x16 function is released.
