### ISSUE TITLE
Visual Studio 2019 Compile Error LNK2019

### ISSUE THREAD

**Issue by Body-Alhoha** [SleepMod/Overwrite-MBR#2]
Hello , i get this error when i try to compile it , how to fix it ?
![image](https://user-images.githubusercontent.com/50592096/99077489-1c5f8200-25bd-11eb-9cc9-822458da221f.png)

**Comment by Body-Alhoha** [comment]
Oh wait i found ! it works ! Thank you for this project so cool ^^

**Comment by Zordon1337** [comment]
how did you fixed that i have same problem but i don't know how to fix it

**Comment by Body-Alhoha** [comment]
learncpp.com

**Comment by Zordon1337** [comment]
anyways i fixed it
